- src/components/headings/README.md
- src/components/headings/heading-highlighted.twig
- src/components/headings/heading-long.twig
- yarn.lock
Added readMe. Removed no longer required templates from headings. Excluded yarn.lock from repo.
> Add readme and remove nlr templates.

- src/components/accordions/accordions.scss
Remove bottom borders .card-foldable and apply to .accordion.
> WS-279: Updated borders on accordions.

- renovation.info.yml
- templates/page/page.html.twig
Several regions within the header are no longer required. This PR removes tem.
> Remove regions in header that are NLR by the design.

- src/sass/variables/_colors.scss
I have updated the focused state as per @imorale2 request. To be honest this seems a bit heavy handed and will possibly cause issues if there is for instance gold text.
This fixes the issue for now but most likely this will need another visit.
> Updated the focus state to the correct color as per the XD Design.

- src/components/heroes/heroes.twig
Removed if preventing button showing on small heroes.
> Allow button to be shown on small hero.

- src/components/heroes/heroes.twig
This was incorrectly reported as a bug so reverting.
> Revert as incorrectly reported as bug.

- src/components/story-hero/story-hero.scss
- src/sass/bootstrap-asu-extends.scss
- templates/layouts/onecol-article-hero-section.html.twig
> Ws2 311 hero

- src/components/breadcrumb/breadcrumb.twig
- src/sass/extends/_breadcrumb.scss
> Update SASS and template to latest storybook version.

- src/sass/extends/_buttons.scss
- src/sass/extends/_card-arrangements.scss
Apply latest updates of Unity SASS for buttons and card arrangements.
> Ws2-463: Update UDS components Sass to latest version of UNity Sass.

- src/components/block/block.scss
- src/components/block/image-block.twig
- src/sass/bootstrap-asu-extends.scss
Template adjusted to allow 100% width. CSS overridden to allow 100% width as .uds_img limits width to 900px;
> Allow images to fill container.

- includes/paragraph.inc
- src/components/accordions/accordion.twig
- templates/block/block--inline-block--accordion.html.twig
Update Accordion to latest storybook. Allows special characters to be used in header.
> Update templates to latest storybook.

- src/components/blockquote/blockquote-image.twig
- src/components/blockquote/blockquote.twig
- templates/block/block--inline-block--blockquote.html.twig
- templates/paragraphs/paragraph--blockquote.html.twig
WS2-221: Blockquotes Templates [Front-end]- Develop
> Rebuild bloqckquote component

- includes/form.inc
- src/components/_form-overrides.scss
- src/components/story-hero/story-hero.scss
- src/sass/bootstrap-asu-extends.scss
- templates/block/block--pagetitle.html.twig
Add page title back to LB forms and User login. Convert link to button and provide spacing.
> Add page title back to LB forms and Login form.

- css/ckeditor-override.css
- src/components/lists/_lists.scss
- src/components/lists/test.twig
- src/sass/bootstrap-asu-extends.scss
Overrides to allow lists to function to work in ckeditor.
> WS2-459: Overrides to allow lists to function to work in ckeditor.

- src/components/breadcrumb/_breadcrumb.scss
Ensure breadcrumb aligns on mobile.
> Ws2 315 Breadcrumb alignment on mobile

- templates/paragraphs/paragraph--basic-list.html.twig
- templates/paragraphs/paragraph--display-list-item.html.twig
- templates/paragraphs/paragraph--display-list.html.twig
- templates/paragraphs/paragraph--icon-list-item.html.twig
- templates/paragraphs/paragraph--icon-list.html.twig
- templates/paragraphs/paragraph--level-1.html.twig
- templates/paragraphs/paragraph--level-2.html.twig
- templates/paragraphs/paragraph--level-3.html.twig
- templates/paragraphs/paragraph--level-4.html.twig
- templates/paragraphs/paragraph--level-5.html.twig
- templates/paragraphs/paragraph--level-6.html.twig
- templates/paragraphs/paragraph--list-item-simple--default.html.twig
- templates/paragraphs/paragraph--multi-level-list.html.twig
- templates/paragraphs/paragraph--ordered-level-1.html.twig
- templates/paragraphs/paragraph--ordered-level-2.html.twig
- templates/paragraphs/paragraph--ordered-level-3.html.twig
- templates/paragraphs/paragraph--ordered-level-4.html.twig
- templates/paragraphs/paragraph--ordered-level-5.html.twig
- templates/paragraphs/paragraph--ordered-level-6.html.twig
- templates/paragraphs/paragraph--ordered-multi-level-list.html.twig
- templates/paragraphs/paragraph--step-list-item.html.twig
- templates/paragraphs/paragraph--step-list.html.twig
This PR removes the paragraph templates for lists built from paragraphs.
> WS2-228: Remove obsolete templates for paragraph lists.

- templates/block/block--inline-block--testimonial.html.twig
- templates/paragraphs/paragraph--testimonial.html.twig
I added the necessary templates for the integration of the react core component.
> Add testimonial templates

- src/components/banners/_banners.scss
A recent change to Unity which adds a 16px left margin to the second button has bled through to the notifications buttons. Some things need to be more specific !!!!
> Remove margin from second button.

- src/components/cards/_card-and-image.scss
- src/components/cards/_card-image-and-content.scss
- src/components/cards/card-and-image.twig
- src/components/cards/card-arrangement.twig
- src/components/cards/card-image-and-content.twig
- src/components/image-overlap/image-overlap.twig
- src/sass/bootstrap-asu-extends.scss
- src/sass/extends/_card-and-image.scss
- templates/block/block--inline-block--card-and-image.html.twig
- templates/block/block--inline-block--card-image-and-content.html.twig
- templates/block/block--inline-block--content-image.html.twig
- templates/field/field--block-content--field-heading--card-image-and-content.html.twig
- templates/field/field--paragraph--field-icon--anchor-menu-settings.html.twig
WS2-460: Content Sections
Integration of the following components:
- Card and Image
- Card Image and Content
- Content Image Overlap Right
- Content Image Overlap Left
> Content sections

- templates/field/field-menu-item.html.twig
Remove extra title that was displaying in block.
> WS2-596: Remove H2 title.

- src/components/cards/cards.scss
- src/sass/extends/_card-image-and-content.scss
- src/sass/extends/_cards.scss
- templates/paragraphs/paragraph--card--landscape.html.twig
- templates/paragraphs/paragraph--card--portrait.html.twig
- templates/paragraphs/paragraph--card-degree--landscape.html.twig
- templates/paragraphs/paragraph--card-degree--portrait.html.twig
- templates/paragraphs/paragraph--card-event--landscape.html.twig
- templates/paragraphs/paragraph--card-event--portrait.html.twig
- templates/paragraphs/paragraph--card-story--landscape.html.twig
- templates/paragraphs/paragraph--card-story--portrait.html.twig
- templates/paragraphs/paragraph--card-with-icon--landscape.html.twig
- templates/paragraphs/paragraph--card-with-icon--portrait.html.twig
Update from unity: UDS-669 Content sections: Card, image, content fix card issues
> Update conten sections: card-image-and-content

- src/components/grid-links/grid-links.twig
- src/components/tabbed-panels/tabbed-panels.js
- src/components/tabbed-panels/tabbed-panels.twig
- src/sass/extends/_tabbed-panels.scss
WS2-406: Update tabs to latest Unity.
WS2-655: Grid Links: blocks break page margins on mobile devices
> Update tabbed-panels & grid links to the latest version

- src/components/headings/heading-highlighted.twig
- src/components/heroes/_heroes.scss
- src/components/heroes/heroes.twig
- src/components/sidebar/_sidebar.scss
- src/sass/extends/_heroes.scss
- src/sass/extends/_sidebar.scss
- templates/block/block--inline-block--hero.html.twig
Renovation updated to the latest version of the Hero in Unity.
> Ws2 647: Update Renovation to the latest version of the hero

- src/components/blockquote/blockquote-image.twig
- src/components/grid-links/grid-links.twig
- src/sass/extends/_blockquotes.scss
- src/sass/extends/_global-header.scss
- src/sass/extends/_globalfooter.scss
- src/sass/extends/_grid-links.scss
- src/sass/extends/_tabbed-panels.scss
- templates/block/asu-footer--footer-block.html.twig
- templates/block/block--inline-block--tabbed-content.html.twig
-  Update tabbed-content template
-  Update grid links template
- Update footer template
- Updates from unity
- Fix blockquote template
> Updates for RC2

- src/components/heroes/heroes.twig
- src/sass/extends/_heroes.scss
Prevent empty button from printing.
> ws2-697: Prevent button from printing when empty.

- src/components/cards/card-arrangement.twig
- src/sass/extends/_card-arrangements.scss
- templates/paragraphs/paragraph--card--landscape.html.twig
- templates/paragraphs/paragraph--card--portrait.html.twig
- templates/paragraphs/paragraph--card-degree--landscape.html.twig
- templates/paragraphs/paragraph--card-degree--portrait.html.twig
- templates/paragraphs/paragraph--card-story--landscape.html.twig
- templates/paragraphs/paragraph--card-story--portrait.html.twig
- templates/paragraphs/paragraph--card-with-icon--landscape.html.twig
- templates/paragraphs/paragraph--card-with-icon--portrait.html.twig
WS2-696 : Card arrangements - 3 column display
Update card template with new fields to add option clickable to cards
> Update card arrangement

- src/components/alerts/_alerts.scss
- src/components/alerts/alert.twig
Notifications were missing the grey border on the close button. This PR adds it back.
> Add grey border to close button.

- src/components/image/_images.scss
- src/sass/bootstrap-asu-extends.scss
Fix images overlapping drop shadow. Added margin to bottom of images where drop shadow is applied.
> ws2-454: Fix images overlapping drop shadow.

- src/components/block/block.scss
- src/components/page404/page404.scss
- src/components/regions/regions.scss
- src/sass/bootstrap-asu-extends.scss
Refactored the code from the 404 page pull and added the fixes for the white background.
> Refactor regions and 404 and fix whitebg. See WS2-719.

- src/components/image/_images.scss
I created a new PR form: https://github.com/ASUWebPlatforms/webspark-theme-renovation/pull/161/ to get rid of the conflicts.
I pulled the latest from main in local -> created this branch from that -> cherry-pick(ed) Anthony's commint from the branch used for the other PR -> resoved conflicts -> created this PR
> WS2-707: Fixes for image embeds.

- src/components/alerts/_alerts.scss
- src/components/modals/_modals.scss
This replaces https://github.com/ASUWebPlatforms/webspark-theme-renovation/pull/158 after fixing conflicts.
> Fixes for modal windows.

- src/components/cards/card-arrangement.twig
- src/components/image-background-with-cta/image-background-with-cta.twig
- src/sass/extends/_banners.scss
- src/sass/extends/_image-background-with-cta.scss
- src/sass/extends/_image-overlap.scss
- Fix card arrangement alignment
- Fix image-background-with-cta
- Fix banner alignment
- Fix image-overlap
> Impot unity bugfixing

- src/sass/block/_block.scss
We agreed with Itzel, as a document (I dont have the link now) stated, that the spacing for the mobile will be half of the spacing for the desktop version.
> Add the spacing for the mobiles. See WS2-907.

- includes/paragraph.inc
- src/components/accordions/accordion.twig
- templates/block/block--inline-block--accordion.html.twig
- templates/paragraphs/paragraph--accordion-panel.html.twig
It was missing the parrent_id and I had to get it from the parent block entity.
> Fix accordion only one open. See WS2-888.

- src/components/block/block.scss
- src/components/image/_images.scss
This sets the WYSIWYG max-width.
> WS2-970: Set max-width to WYSIWYG image elements

- src/components/_form-overrides.scss
This fixes the buttons misalignment as described at https://asudev.jira.com/browse/WS2-803 .
> WS2-803: Fix button misalignment.

- src/components/tooltips/tooltip.twig
- src/components/tooltips/tooltips.js
https://asudev.jira.com/browse/WS2-603
> #WS2-603.Add tooltips JS. This will enable to close the tooltip on mobile on pressing the tooltip icon.

- src/components/ckeditor/ckeditor.scss
https://asudev.jira.com/browse/WS2-587
https://asudev.jira.com/browse/WS2-589
> #WS2-582. Fix edit media button. Fix remote video display inside the ckeditor.

- src/components/tabbed-panels/_tabbed-panels.scss
@duarte-daniela @mlsamuelson this removes the arrows in tabbed content.
Ref.: https://asudev.jira.com/browse/WS2-938
> WS2-938: Remove arrows in tabbed content.

- src/components/_form-overrides.scss
@duarte-daniela @mlsamuelson this modifies the `media-library-widget` form layout.
Ref.: https://asudev.jira.com/browse/WS2-443
> WS2-443: Remove double asterisk.

- src/components/accordions/accordions.scss
@duarte-daniela @mlsamuelson this fixes the accordion panel margins.
Ref.: https://asudev.jira.com/browse/WS2-1124 .
> WS2-1124: Alter accordion panel margins.

- src/components/divider/divider.twig
- templates/block/block--inline-block--divider.html.twig
@duarte-daniela @mlsamuelson this allows setting a divider type.
Ref.: https://asudev.jira.com/browse/WS2-1108
> WS2-1108: Set Divider type.

- src/components/tabbed-panels/tabbed-panels.twig
@duarte-daniela @mlsamuelson this reveals the tabbed content.
Ref.: https://asudev.jira.com/browse/WS2-999?focusedCommentId=1385973
> WS2-999: Unhide the tabbed content.

- src/components/tables/tables.js
- src/sass/extends/_tables.scss
Updated the css and the js for the tables
> Update tables component.

- src/components/node/_node.scss
@duarte-daniela @mlsamuelson this decorates the unpublished node.
Ref.: https://asudev.jira.com/browse/WS2-1141
> WS2-1141: Decorate the unpublished nodes.

- templates/block/block--inline-block--webform.html.twig
@duarte-daniela @mlsamuelson this adds the Webform custom block where Appearance Settings could be set.
> WS2-1144: Create custom webform block.

- includes/block.inc
- src/components/tabbed-panels/tabbed-panels.twig
@duarte-daniela @mlsamuelson this adds the block_field related functionality.
Ref.: https://asudev.jira.com/browse/WS2-1142
> WS2-1142: Enable block_field module functionality.

- templates/block/asu-footer--footer-block.html.twig
@duarte-daniela @mlsamuelson this adds the footer menu stacking.
Ref.: https://asudev.jira.com/browse/WS2-1093
> WS2-1093: Footer menus stacking.

- src/components/image-text-block/_image-text-block.scss
- src/sass/bootstrap-asu-extends.scss
@duarte-daniela @mlsamuelson this fixes the padding in the `Image and Text Block` component.
Ref.: https://asudev.jira.com/browse/WS2-1115
> WS2-1115: Fix Image and Text Block.

- templates/navigation/asu-pager.html.twig
@duarte-daniela @mlsamuelson this adds the `Show Icons` option.
Ref.: https://asudev.jira.com/browse/WS2-1139?focusedCommentId=1397176
> WS2-1139: Alter Prev/Next arrows display.

- src/components/anchors/_anchors.scss
@duarte-daniela @mlsamuelson this reduces the top scroll padding.
Ref.: https://asudev.jira.com/browse/WS2-720?focusedCommentId=1395658
> WS2-720: Reduce scroll-pading-top.

- src/components/global-footer/global-footer.scss
- src/sass/bootstrap-asu-extends.scss
- src/sass/extends/_globalfooter.scss
- templates/page/page.html.twig
Stick footer to bottom of page.
@mlsamuelson as we discussed we add the styles in WS2.
Test site: https://stable-v3-dept-stable-release.ws.asu.edu/
Ticket: https://asudev.jira.com/browse/WS2-1176
> WS2-1176: Footer issues

- src/components/tabbed-panels/tabbed-panels.twig
This will clash slightly with @chill5-0's work on WS-1204, so I'm adding her as a reviewer. From what I can see, there are a few attributes Cameo added that I didn't add, and one that I added that she didn't ("data-ga"). Also, on line two, I have added a class: "uds-content-align."
> webspark-release: update tabbed-panels.twig to match unity

- src/components/anchors/_anchors.scss
@duarte-daniela @mlsamuelson this removes the smooth scrolling and further adjust the top scroll padding.
Ref.: https://asudev.jira.com/browse/WS2-720?focusedCommentId=1399178
> WS2-720: Remove smooth scrolling

- js/datalayer.js
- src/components/accordions/accordion.twig
- src/components/banners/banners.twig
- src/components/buttons/button-cta.twig
- src/components/buttons/button-icon.twig
- src/components/buttons/button-tag.twig
- src/components/heroes/heroes.twig
- src/components/links/cta-link.twig
- src/components/links/link-icon.twig
- src/components/links/link.twig
- src/components/links/tags.twig
- src/components/pager/pager.twig
- src/components/sidebar/sidebar.twig
- src/components/tabbed-panels/tabbed-panels.twig
- src/components/tabs/tabs.twig
> Datalayer reboot

- .gitignore
- README.md
- config.js
- webpack.mix.js
- Also created a core config.js file
- This serves as the example file, and can be used in the future to store configurations should the current webpack file grow out of hand
> Add a new file to store local development server information

- includes/form.inc
This PR adds descriptive text to the Media Item "edit media" dialog box.
See https://asudev.jira.com/browse/WS2-592?focusedCommentId=1488343.
> Add description text to media item dialogs regarding Remote Videos.

- .gitignore
- assets/mix-manifest.json
- config.js
- src/components/_form-overrides.scss
- src/sass/base/_drupal-admin-tweaks.scss
@mlsamuelson I have not included a Sass compilation here, in case we have any more updates to add before we do the WS2 release. But, if you'd like me to compile it, I can push the compiled files up as well.
Also, this adds some code that will hopefully make theme editing easier for everyone. It allows for source maps to be created locally, which will help us find where styles and scripts are being set in Sass.
> ASUIS-482: [QA Webdir]: config menu hint text has no contrast against background

- templates/field/field--block-content--field-heading--content-image.html.twig
The version submitted in the PR was the old version of this file. This PR includes the new version, which should have been submitted the first time around.
> WS2-1130: Update twig file to include the proper heading

- src/sass/content/_theme-tweaks.scss
See: https://asudev.jira.com/browse/WS2-1293
Just some small CSS tweaks.
> WS2-1293: Fix CSS on the skip links to avoid the extra padding

- src/components/block/block.scss
See: https://asudev.jira.com/browse/WS2-1373
> WS2-1373: Adjust the Video Hero poster image scale

- js/global-header.js
During the ws2-1148 task, I came across this code that was duplicated. Seems to be accidental, so removing the duplicate code.
> Remove duplicated code in global-header.js

- src/sass/layout/_page.content.scss
See: https://asudev.jira.com/browse/WS2-1243
- Add CSS to fix extra white space in the main element
> WS2-1243: Add CSS to fix extra white space in the main element

- src/sass/layout/_page.content.scss
- These were accidentally removed during the merge conflict resolution
> QUICK FIX: Add back the missing closing brackets

- templates/navigation/links.html.twig
https://asudev.jira.com/browse/WS2-1508
> add links.html.twig from bartik to fix radix problem

- src/sass/content/_theme-tweaks.scss
See: https://asudev.jira.com/browse/WS2-1536
> WS2-1536: Fix the hover color on pagination links

- src/sass/extends/_tables.scss
Ticket: https://asudev.jira.com/browse/WS2-1081
> WS2-1081: Unity Design - Webspark Table Modal Fixes: Appropriate styling in Unity, Table Caption, Additional Spacing on sibling tables
