src/components/banners/_banners.scss

The close icons were changed to FA5. This required some css to override original functionality. This corrects an issue on mobile only.

REmove negative margin from close button on mobile.

---

src/components/breadcrumb/_breadcrumb.scss

The breadcrumb <nav> has a container class. This container I believe should be 1200px. When applied to the breadcrumb it is actually 1220px. I have corrected this for the breadcrumb only. Will report this issue back to Unity in case something has broken their end. Removed padding for all colors including white.

WS2-413: Fix width issue on breadcrumb

---

src/components/breadcrumb/_breadcrumb.scss
src/components/layouts/layouts.scss
src/components/story-hero/story-hero.scss
src/sass/bootstrap-asu-extends.scss
templates/layouts/onecol-article-hero-section.html.twig

Added div with a container class to wrap h1 as it was not scaling fluidly and consistently with the breadcrumb. Restricted the container width to 992px on articles only. This is to ensure the text or other components align with the heading and breadcrumb.

ws2-477: fix padding on story hero title region.

---

src/components/alerts/alert.twig

Drupal provides four status message types in D9. Currently we do not have a status for danger in css. Font awesome provides an icon for 'error' which is also used for 'danger'. I have added the status 'danger' to the template using the same icon as 'error' until an alternative is found so we don't display a faulty icon.
@imorale2 This needs a discussion

Drupal provides an extra status for alerts.

---

src/components/lists/_lists.scss

Added the styles on the svg inside the icon lists  because we couldnt add the fa-li class. The contrib module is processing this code.

Styling for the svg inside lists.

---

css/ckeditor-override.css
src/components/tooltips/_tooltips.scss

Font Awesome <i> tags get converted to SVG's in CKEditor. This PR uses the fill attribute to set colors rather than color. The excess space around the icon has been removed to allow the icon to sit within the text more comfortably.

CSS overrides for ckeditor tooltips.

---

templates/block/block--inline-block--hero.html.twig

The Hero required two CTA's. As the existing CTA was used elsewhere, updating its cardinality was an issue. A new field was added and the changes to the template support this change."

Update template to support new field for multiple CTA's.

---

src/components/story-hero/story-hero.scss

Fixes in this PR
- Add margins to fixed width layout regions specifically for Article content type to align with storybook.
- Remove padding from Article type on containers for title and breadcrumb to align correctly with Storybook.

WS2-677: Overrides to correct alignment on Article content types.

---

renovation.libraries.yml

For annon users, this library doesn't load by default so we must add it as a dependency.

Add jquery.once dependency.

---

css/ckeditor-override.css
src/components/tooltips/_tooltips.scss
src/sass/extends/_media_embed.scss

Correct alignment issues in/from CKE and position button so it does not break alignment when embedding.
Replacement for https://github.com/ASUWebPlatforms/webspark-theme-renovation/pull/151

WS2-302: Overrides required for CKE to use spans for tooltips as div cannot be embedded in <p> element.

---

css/ckeditor-override.css
src/components/_form-overrides.scss

This reverts the radio buttons format on webforms and keeps the fixed format on layout overlay forms.
Ref.: https://asudev.jira.com/browse/WS2-893

WS2-893: Revert radio buttons on webforms.

---

src/components/cards/cards.scss

@duarte-daniela @mlsamuelson this removes the space when no card icon was selected.
Ref.: https://asudev.jira.com/browse/WS2-1131

WS2-1131: Remove empty icon space.

---

src/components/text/_text.scss

@duarte-daniela @mlsamuelson this fixes the link focus outline in rich text links, including Font Awesome icons as hyperlinks.
Ref.: https://asudev.jira.com/browse/WS2-1120

WS2-1120: Font Awesome link focus.

---

src/components/heroes/_heroes.scss

@duarte-daniela @mlsamuelson this fixes the Hero sub-heading appearance.
Ref.: https://asudev.jira.com/browse/WS2-400

WS2-400: Fix Hero sub-heading.

---

renovation.libraries.yml
src/components/charts-and-graphs/donut.twig

@duarte-daniela @mlsamuelson this fixes the display of Donut charts in Renovation sub-themes. 
Ref.: https://asudev.jira.com/browse/WS2-1162

WS2-1162: Include charts_graphs in libraries.yml.

---

src/components/cards/card-and-image-parallax.js

@duarte-daniela @mlsamuelson this removes the image resizing in the parallax related functionality.
Ref.: https://asudev.jira.com/browse/WS2-997?focusedCommentId=1397035

WS2-997: Remove image resize in Card And Image component.

---

src/components/tooltips/tooltips.js

@duarte-daniela @mlsamuelson this fixes the toolitp display in iPhone.
Ref.: https://asudev.jira.com/browse/WS2-603?focusedCommentId=1397188

WS2-603: Fix tooltip display in iPhone.

---

src/sass/content/_theme-tweaks.scss
src/sass/renovation.style.scss
templates/page/page.html.twig
templates/system/html.html.twig

I ended up choosing to keep the two different skip-to-main-content links, but employed some logic so that if the toolbar was available, the non-header one would be used. This will bypass all of the links in the toolbar, which will improve the experience regardless of whether a user has toolbar access or not.

WS2-1276: Fix skip-to-main-content issue

---

templates/field/field--block-content--field-heading--content-image.html.twig

This PR is part of a larger fix, see https://asudev.jira.com/browse/WS2-1130
This adds a new field template for the heading used by the Content Image Overlap block. This heading is optional, but when it is used, it will always appear as an `h2` element and highlighted gold.

WS2-1130: Add new template to allow changing the heading element

---

templates/field/field--node--title.html.twig

Was getting `Twig\Error\SyntaxError: Unexpected end of template. in Twig\TokenStream->next() (line 17 of /code/web/themes/composer/webspark-theme-renovation/templates/field/field--node--title.html.twig).`

WS2 release 2.6.0 fix twig syntax

---

src/sass/extends/_form-fields.scss
src/sass/renovation-extends/_form-fields.scss
src/sass/renovation.style.scss

See: https://asudev.jira.com/browse/WS2-1219
Quick CSS fix to prevent the checkbox inputs for the Table Select field type from being transparent.
This code might be in the wrong place.

WS2-1219: Remove opacity from Table Select form fields inputs

---

package.json

This PR is to get a quick conversation going. Right now we have the `config.js` but we need to manually copy it to `config.local.js`. I always forget to do this, so I added some code to the `postinstall` to automatically do it for me.
Is this something that would be useful to everyone, or should I just keep this to my own workflow?
PROS: Don't need to remember to manually create `config.local.js`
CONS: If you have to re-install the theme a lot, you will need to update the `proxy` value each time, assuming that you use the BrowserSync functionality. And since this will create a new `config.local.js` each time, any custom code in here would also need to be added back.

Automatically create the config.local.js file

---

src/components/accordions/accordions.js
src/components/tabbed-panels/tabbed-panels.js

See: https://asudev.jira.com/browse/WS2-1033
NOTE: Tabs have a reserved name in them. #nav-tab is hard-coded in Twig, so users need to be aware that a Tab with the name of “Tab” will result in #nav-tab being duplicated on the page, and this hashing will not work.

WS2-1033: Integrate the hash events for Accordions and Tabbed Panels

---

templates/page/page.html.twig

Simple fix in page.html.twig file caps the width at 1920px and centers those divs. Only blocks put in regions outside the pre-content and content divs in the page template (the global ASU header/footer, megafooter, etc.) will go 100% wide now.

WS-1515 - Added classes to page TWIG to stop super-wide content items
